### ISSUE TITLE
`p` crashes program

### ISSUE THREAD

**Issue by zuixalias** [WillEccles/cfm#34] opened 2023-02-06 14:48 UTC
If i paste a file (which i yanked with `yy`) in the same folder...it crashes the app.
(Probably because a file with the same name already exists) (or if that is handled then could be related to the `shell script as $EDITOR`...idk though)

**Comment by sophec** [comment] 2023-02-06 14:50
This is a duplicate of #32. It will attempt to open the editor so that you can enter an alternative name.

**Closed as not planned by sophec** 2023-02-06 14:50 UTC
